version: '3.1'
services:
  mysql-api:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: validatorAPP
    ports:
      - "3307:3306" 

  admin:    
    image: adminer    
    ports:      
      - "8080:8080"

  my-validate-api:    
    image: m74cpfcnpj:latest 
    container_name: m74cpfcnpj 
    ports:      
      - "5000:5000"
    depends_on:
      - mysql-api

    # Reference https://betterprogramming.pub/setting-up-mysql-database-in-a-docker-d6c69a3e9afe